name: "Bug Report"
description: "File a bug report for a problem with the mod."
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "Thanks for filling out a bug report!"
  - type: textarea
    id: problem-description
    attributes:
      label: "What happened?"
      description: "Describe the problem as best you can."
      placeholder: "A clear description of the bug."
    validations:
      required: true
  - type: textarea
    id: expectation-description
    attributes:
      label: "What did you expect to happen?"
      description: "Describe what should have happened instead as best you can."
      placeholder: "A clear description of the expected behavior."
    validations:
      required: true
  - type: input
    id: silksong-version
    attributes:
      label: "Silksong Version"
      description: "What version of Silksong are you running?"
      placeholder: "1.0.29242"
    validations:
      required: true
  - type: dropdown
    id: mod-version
    attributes:
      label: "Mod Version"
      description: "What version of the mod are you running?"
      options:
        - "1.0.0"
      default: 0
    validations:
      required: true
  - type: input
    id: other-mods
    attributes:
      label: "Other Mods"
      description: "Are you using any other mods that might affect this one?"
    validations:
      required: false
  - type: textarea
    id: log-lines
    attributes:
      label: "Log Lines"
      description: "Please include any relevant lines from your `BepInEx/LogOutput.log` file:"
      placeholder: "[Error  :   BepInEx] ..."
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: "Anything else?"
      description: "Do you have any other information to include?"
      placeholder: "..."
    validations:
      required: false
